#! /usr/bin/env bash

set -e

pythonver=$(python --version 2>&1 | awk -F'.' '{print $1}')

# Create user if it doesn't exist
if ! id graphite > /dev/null 2>&1 ; then
	adduser --system --home /usr/share/python/graphite --no-create-home \
		--ingroup nogroup --disabled-password --shell /bin/false \
		--gecos 'Graphite API' \
		graphite
fi

# Create path if it doesn't exist
if ! test -d /srv/graphite ; then
	mkdir -p /srv/graphite
	chown graphite:nogroup /srv/graphite
	chmod -R 750 /srv/graphite
fi

# Register service
if [ -x "/etc/init.d/graphite-metrictank" ]; then
	update-rc.d graphite-metrictank start 50 2 3 4 5 . stop 50 0 1 6 . >/dev/null
	invoke-rc.d graphite-metrictank start || exit $?
fi
