#! /usr/bin/env bash
set -e

find /usr/share/python/graphite/lib -iname *.pyc -exec rm {} \;
find /usr/share/python/graphite/lib -iname *.pyo -exec rm {} \;

if [ -x "/etc/init.d/graphite-raintank" ]; then
	invoke-rc.d graphite-raintank stop || exit $?
fi
